services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netresearch\ContextsDevice\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Dto/*'
      - '../Classes/Exception/*'

  # DeviceDetector instance - Matomo DeviceDetector library
  # No configuration needed - uses user-agent from request
  DeviceDetector\DeviceDetector:
    shared: false
